name: CI for Pull Requests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: ["!master"]
jobs:
  deploy:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        name: Clone the repository
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        name: Install Node.JS
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ${{env.STORE_PATH}}
          key: ${{runner.os}}-pnpm-cache-${{ hashFiles('./pnpm-lock.yaml')}}
          restore-keys: ${{runner.os}}-pnpm-cache-
      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile
      - name: Build website
        shell: bash
        run: pnpm build
